gpu_models:
  3090Ti: 1
  4090D: 2
  '5090': 3
master:
  host: 10.61.16.33
  port: 8080
  web_port: 5000
results:
  dir: /home/handb/poolgpu/results
retry:
  delay_seconds: 5
  max_attempts: 3
servers:
- gpu_model: '5090'
  gpus: 2
  host: 10.62.193.36
  name: server1
  user: handb
sync:
  code_dir: /home/handb/PoolGPU
  env_name: myenv
  env_pack_path: /tmp/myenv.tar.gz
worker:
  port: 8090
  report_interval: 10
